import time

print("Pour crypter un  message, il faut utiliser le  dossier chiffrement1.py")
time.sleep(1)
print("voici de quelle maniere il faut ecrire le message afin de le chiffrer")
time.sleep(1)
print("si je  veux ecrire attaque, j'ecris : ")
time.sleep(1)
print("a")
time.sleep(1)
print("t")
time.sleep(1)
print("t")
time.sleep(1)
print("a")
time.sleep(1)
print("q")
time.sleep(1)
print("u")
time.sleep(1)
print("e")
time.sleep(1)
print("0")
time.sleep(1)
time.sleep(1)

print("vous remarquerez le 0, il y a  8 entree de lettres, lorsque  le mot est  ecrit entierement,  il suffit de  continuer avec des 0 jusqu'a ce que les 8 caracteres  soient remplis")
time.sleep(1)
print("si je veux  ecrire IP , alors j'ecrirais")
time.sleep(1)
print("I")
time.sleep(1)
print("P")
time.sleep(1)
print("0")
time.sleep(1)
print("0")
time.sleep(1)
print("0")
time.sleep(1)
print("0")
time.sleep(1)
print("0")
time.sleep(1)
print("0")
time.sleep(1)

print("a  chaque nouvelle  lettre, il faut  appuyer sur entrer")
time.sleep(1)


print("////////  etape 2")
time.sleep(1)
print("la premiere partie de dechiffrement")
time.sleep(1)
print("il  faut ouvrir chiffrement2.py,  puis y entrer les nombres deduis dans chiffrement1")

time.sleep(1)
print("/////// etape 3")
time.sleep(1)
print("il faut indiquer  les  nombres  deduis dans  chiffrement2")

print("exemple :")

print("commencer ? oui / non")
print("oui")
print("votre mot")
print("a")
print("t")
print("t")
print("a")
print("q")
print("u")
print("e")
print("0")
print("53")
print("23304312")
print("continuer ? oui / non")
print("non")
print("LS:crypteur root$ python  chiffrement2.py")
print("phase 1")
print("53")
print("phase 2")
print("23304312")
print("('lettre 1 : ', 53)")
print("('valeur du mot : ', 763)")
print("LS:crypteur root$ python  chiffrement3.py")
print("Ecrivez : a ; puis la premiere lettre (exemple : a5678)  : ")
print("a53")
print("Ecrivez : b ; suivi de la valeur du mot : ")
print("b763")
print("('le mot est :', 'a', 'attaque')")
